import { GarmentBOM } from './types';

export const bomPresets: Record<string, GarmentBOM> = {
  hoodie: {
    garmentType: 'Oversized French Terry Hoodie (450 GSM)',
    fabricItems: [
      {
        id: 'fab-1',
        name: 'Main Body Fabric',
        material: '100% Combed Compact Cotton Loopback French Terry',
        weightGsm: 450,
        consumption: 0.95,
        unit: 'kg',
        ratePerUnit: 720,
        totalCost: 684,
      },
      {
        id: 'fab-2',
        name: 'Cuffs, Hem & Side Panels',
        material: '2x2 Cotton Elastane Heavy Rib Knit',
        weightGsm: 420,
        consumption: 0.18,
        unit: 'kg',
        ratePerUnit: 580,
        totalCost: 104.4,
      },
      {
        id: 'fab-3',
        name: 'Double-Layered Hood Lining',
        material: 'Single Jersey Combed Cotton Lining',
        weightGsm: 180,
        consumption: 0.20,
        unit: 'kg',
        ratePerUnit: 480,
        totalCost: 96,
      },
    ],
    stitchingLabor: 180, // CMT cut, flatlock stitching, double needle seaming
    washFinishCost: 65,  // Reactive piece dye & carbon suede soft-wash
    trimItems: [
      {
        id: 'trm-1',
        name: 'Braided Heavy Cotton Drawcord',
        category: 'Trims & Hardware',
        specification: '12mm round hollow cotton cord, natural unbleached',
        quantity: 1,
        ratePerUnit: 25,
        totalCost: 25,
      },
      {
        id: 'trm-2',
        name: 'Laser-Engraved Gunmetal Aglets',
        category: 'Trims & Hardware',
        specification: 'Matte dark gunmetal with Rivlet micro-insignia',
        quantity: 2,
        ratePerUnit: 15,
        totalCost: 30,
      },
      {
        id: 'trm-3',
        name: 'Reinforced Metal Eyelets',
        category: 'Trims & Hardware',
        specification: 'Matte brass eyelets with washer backing',
        quantity: 2,
        ratePerUnit: 6,
        totalCost: 12,
      },
      {
        id: 'trm-4',
        name: 'High-Density Damask Neck Label',
        category: 'Labels & Packaging',
        specification: '50-denier woven damask with satin border',
        quantity: 1,
        ratePerUnit: 14,
        totalCost: 14,
      },
      {
        id: 'trm-5',
        name: 'Satin Care & Composition Label',
        category: 'Labels & Packaging',
        specification: 'Black satin ribbon with QR traceability code',
        quantity: 1,
        ratePerUnit: 6,
        totalCost: 6,
      },
      {
        id: 'trm-6',
        name: '600 GSM FSC Hangtag with Wax Seal',
        category: 'Labels & Packaging',
        specification: 'Embossed gold foil, tactile uncoated cardstock, cotton cord',
        quantity: 1,
        ratePerUnit: 18,
        totalCost: 18,
      },
      {
        id: 'trm-7',
        name: 'Custom Frosted Zip-Lock Polybag',
        category: 'Labels & Packaging',
        specification: 'Frosted biodegradable EVA bag with breathable valve',
        quantity: 1,
        ratePerUnit: 28,
        totalCost: 28,
      },
      {
        id: 'trm-8',
        name: 'Tissue Wrapping & Silica Gel',
        category: 'Labels & Packaging',
        specification: 'Acid-free embossed tissue paper + 2g silica packet',
        quantity: 1,
        ratePerUnit: 6,
        totalCost: 6,
      },
    ],
    totalBOMCost: 1266.4,
    notes: 'Premium 450 GSM French Terry construction calibrated for luxury streetwear drape, zero torque, and <3% shrinkage.',
  },

  tshirt: {
    garmentType: 'Signature Heavyweight Boxy T-Shirt (280 GSM)',
    fabricItems: [
      {
        id: 'fab-1',
        name: 'Main Body Fabric',
        material: '100% Combed Compact Cotton Jersey',
        weightGsm: 280,
        consumption: 0.45,
        unit: 'kg',
        ratePerUnit: 660,
        totalCost: 297,
      },
      {
        id: 'fab-2',
        name: 'Bound Neck Collar Rib',
        material: '1x1 Spun Cotton Lycra High-Spun Rib',
        weightGsm: 320,
        consumption: 0.08,
        unit: 'kg',
        ratePerUnit: 540,
        totalCost: 43.2,
      },
    ],
    stitchingLabor: 95,  // Bound collar, twin-needle cuffs and bottom hem
    washFinishCost: 35,  // Enzyme bio-wash for anti-pilling and silicone softness
    trimItems: [
      {
        id: 'trm-1',
        name: 'High-Density Damask Neck Label',
        category: 'Labels & Packaging',
        specification: 'Heat-sealed edge, anti-scratch yarn',
        quantity: 1,
        ratePerUnit: 14,
        totalCost: 14,
      },
      {
        id: 'trm-2',
        name: 'Exterior Hem Pip Tag',
        category: 'Trims & Hardware',
        specification: 'Micro-woven signature flag label on lower left hem',
        quantity: 1,
        ratePerUnit: 8,
        totalCost: 8,
      },
      {
        id: 'trm-3',
        name: 'Satin Care & Wash Label',
        category: 'Labels & Packaging',
        specification: 'Recycled polyester satin ribbon',
        quantity: 1,
        ratePerUnit: 6,
        totalCost: 6,
      },
      {
        id: 'trm-4',
        name: '600 GSM FSC Hangtag with Seal',
        category: 'Labels & Packaging',
        specification: 'Matte black with gold foil embossing',
        quantity: 1,
        ratePerUnit: 16,
        totalCost: 16,
      },
      {
        id: 'trm-5',
        name: 'Frosted Zip-Lock Packaging Bag',
        category: 'Labels & Packaging',
        specification: 'Frosted biodegradable bag with ventilation hole',
        quantity: 1,
        ratePerUnit: 22,
        totalCost: 22,
      },
    ],
    totalBOMCost: 536.2,
    notes: '280 GSM heavyweight jersey engineered for a structured, drop-shoulder luxury fit with zero transparency.',
  },

  sweatpants: {
    garmentType: 'Relaxed Fit Heavyweight Sweatpants (400 GSM)',
    fabricItems: [
      {
        id: 'fab-1',
        name: 'Main Body Brushed Fleece',
        material: '100% Cotton Premium Brushed Interior Fleece',
        weightGsm: 400,
        consumption: 0.75,
        unit: 'kg',
        ratePerUnit: 690,
        totalCost: 517.5,
      },
      {
        id: 'fab-2',
        name: 'Ankle Cuffs & Rib Waistband',
        material: '2x2 Heavy Spun Rib Knit',
        weightGsm: 420,
        consumption: 0.15,
        unit: 'kg',
        ratePerUnit: 580,
        totalCost: 87,
      },
      {
        id: 'fab-3',
        name: 'Pocket Lining Bags',
        material: 'Single Jersey 180 GSM Cotton Lining',
        weightGsm: 180,
        consumption: 0.12,
        unit: 'kg',
        ratePerUnit: 480,
        totalCost: 57.6,
      },
    ],
    stitchingLabor: 145, // Heavy-duty waistband seaming & concealed zip pockets
    washFinishCost: 55,  // Carbon peach wash & enzyme softening
    trimItems: [
      {
        id: 'trm-1',
        name: 'Cotton Drawcord with Metal Tips',
        category: 'Trims & Hardware',
        specification: '15mm braided flat cotton cord with gunmetal aglets',
        quantity: 1,
        ratePerUnit: 35,
        totalCost: 35,
      },
      {
        id: 'trm-2',
        name: 'YKK Concealed Pocket Metal Zippers',
        category: 'Trims & Hardware',
        specification: 'YKK #4 nylon coil with gunmetal pullers',
        quantity: 2,
        ratePerUnit: 22,
        totalCost: 44,
      },
      {
        id: 'trm-3',
        name: 'High-Density Woven Waistband Label',
        category: 'Labels & Packaging',
        specification: 'Woven loopfold brand label',
        quantity: 1,
        ratePerUnit: 14,
        totalCost: 14,
      },
      {
        id: 'trm-4',
        name: 'Frosted Polybag & Hangtag Package',
        category: 'Labels & Packaging',
        specification: 'FSC hangtag, frosted zip polybag, moisture silica',
        quantity: 1,
        ratePerUnit: 44,
        totalCost: 44,
      },
    ],
    totalBOMCost: 999.1,
    notes: 'Engineered with deep concealed zipped pockets, custom metal eyelets, and reinforced crotch gusset for durability.',
  },
};
